### PR TITLE
perf(validate): improvement of time and memory complexity of validate

### PR DESCRIPTION
**Pull request by whiteand**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x]  **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

- Decreasing of time complexity
- Decreasing of memory complexity

### Changelog

1. Removed usage of map in order to reduce number of memory allocations.
2. Replaced concat with push in order to change complexity from O(n^2) to O(n)

### CODE REVIEW

**Comment by vankop** [comment]
@evilebottnawi LGTM 
could you retrigger CI?

**Comment by evilebottnawi** [comment]
Looks problems with azure pipelines, I will be migrate on github actions in near future

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
