### PR TITLE
fix: typescript definition

### PR DESCRIPTION
**Pull request by yenshih**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
Better TypeScript definition base on control flow analysis for assertions: 
https://github.com/microsoft/TypeScript/pull/32695

```ts
const loader: Loader = function(source) {
    const options = getOptions(this) || {};

    // typeof options --> OptionObject

    validate<SpecificLoaderOptions>(schema, options);

    // typeof options --> SpecificLoaderOptions
};
```

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Oh, it is only for `typescript@3.7` (not released yet)

**Comment by vankop** [comment]
this is great approach, but as @evilebottnawi said already it is for future typescript release

**Comment by yenshih** [comment]
Yes, `typescript@3.7` will be released in 2 weeks. We need to prepare for that. I'm using `typescript@rc` for now.

**Comment by yenshih** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html
ping @evilebottnawi :)

**Comment by vankop** [comment]
declaration now works with JS files 🤩 PR to core webpack confirmed =)

**Comment by yenshih** [comment]
It's fine :)
However, `asserts` is an advanced feature of TypeScript. I have no idea how to use `asserts` in JSDoc.

**Comment by vankop** [comment]
It works same way as in ts files

**Comment by evilebottnawi** [comment]
@vankop can you take care?

**Comment by vankop** [comment]
@evilebottnawi later, maybe on the weekend

**Pull request closed without merging**
