### PR TITLE
chore: update `lint-staged` config

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

update `lint-staged` config.

### Breaking Changes
None

### Additional Info
None

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by snitin315** [comment]
@alexander-akait  can you send me an invite for this repo and other active repos in `webpack`, otherwise I have to use fork and keep rebaisng.

**Comment by alexander-akait** [comment]
I don't have access to all webpack repos, you already invited where I have access, maybe I missed something, feel free to point me where you don't have access

**Comment by snitin315** [comment]
This repo `schema-utils`

**Comment by alexander-akait** [comment]
Done

**Pull request merged**
