### PR TITLE
fix: typescript index.d.ts re-exports

### LINKED ISSUE #114: Can't refer to ValidationError as a type in Typescript
- Operating System: Linux
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version: master
- schema-utils Version: 3.0.0

### Code

```ts
import { ValidationError } from 'schema-utils'
function f(v: ValidationError) {
  console.log(v.errors.length)
}
```

### Expected Behavior

No error in my editor (or when compiling with tsc).

### Actual Behavior

error on `v: ValidationError`: "ValidationError refers to a value, but is being used as a type here."

### How Do We Reproduce?

Paste above code into a file, `tsc --init`, `npm i schema-utils@3`.

Or open webpack's source to lib/util/registerExternalSerializer.js, it has the same problem. You might have to use `typescript@next` or `typescript@beta` to reproduce since I changed the way `require` type checks in Javascript recently.

### Probable Fix

index.d.ts should use the re-export syntax, not exports of import types. I'll put up a PR shortly.

### PR DESCRIPTION
**Pull request by sandersn**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

TODO: I need to find out where the type tests are.

### Motivation / Use-Case

Fixes #114 

### Breaking Changes

Shouldn't break anything, as it exports strictly more than before.

### CODE REVIEW

**Review by evilebottnawi — CHANGES_REQUESTED** [review]
It is auto generated file by typescript, please open an issue in typescript repo

**Comment by sandersn** [comment]
Good point. I'll take a look at the typescript declaration code. One workaround, which I pushed as a separate commit, is to switch index.js to use ES modules, like the rest of the code, since typescript's commonjs+declaration file support is not great. But I'm not sure whether there's a reason to avoid doing this -- is babel running on everything *but* index.js?

**Comment by sandersn** [comment]
If this is not a good workaround, then Typescript 4.1 will contain the fix that generates the correct import/export statements: microsoft/TypeScript#41190

**Comment by evilebottnawi** [comment]
@sandersn big thanks!

**Comment by alexander-akait** [comment]
https://github.com/webpack/schema-utils/issues/114

**Pull request closed without merging**
